/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter;

// JasperReports imports
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

// Koneksi
import koneksi.koneksi;


/**
 *
 * @author Asus
 */
public class FormLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Group radio buttons
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);
        group.add(jRadioButton4);
        
        // Set default selection & date chooser state
        jRadioButton1.setSelected(true);
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        
        // Dynamic date chooser enabling based on radio button selection
        java.awt.event.ActionListener radioListener = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                boolean dateEnabled = jRadioButton3.isSelected() || jRadioButton4.isSelected();
                jDateChooser1.setEnabled(dateEnabled);
                jDateChooser2.setEnabled(dateEnabled);
                if (!dateEnabled) {
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                }
            }
        };
        jRadioButton1.addActionListener(radioListener);
        jRadioButton2.addActionListener(radioListener);
        jRadioButton3.addActionListener(radioListener);
        jRadioButton4.addActionListener(radioListener);
        
        // Add listeners for print and export buttons
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                cetakLaporan();
            }
        });
        
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                exportPDF();
            }
        });
        
        // Load default report on startup (Buku)
        tampilkanLaporan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 247, 245));

        jPanel2.setBackground(new java.awt.Color(99, 102, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel1.setText("  Sistem Informasi Manajemen Perpustakaan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Laporan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(247, 247, 245));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("Laporan Seluruh Data Buku");

        jRadioButton2.setBackground(new java.awt.Color(247, 247, 245));
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Laporan Daftar Anggota");

        jRadioButton3.setBackground(new java.awt.Color(247, 247, 245));
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton3.setText("Laporan Transaksi Peminjaman");

        jRadioButton4.setBackground(new java.awt.Color(247, 247, 245));
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton4.setText("Laporan Pengembalian & Denda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter Periode (Opsional)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Dari Tanggal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Sampai Tanggal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jButton1.setBackground(new java.awt.Color(0, 120, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bxs-report.png"))); // NOI18N
        jButton1.setText("Tampilkan Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(40, 167, 69));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        jButton2.setText("Cetak");

        jButton3.setBackground(new java.awt.Color(220, 53, 69));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/file-export.png"))); // NOI18N
        jButton3.setText("Export PDF");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview Laporan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Laporan Seluruh Data Buku");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Periode : 01/05/2024  s/d  26/05/2026");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(108, 117, 125));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow-back-up-double.png"))); // NOI18N
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampilkanLaporan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new tampilanawal.dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampilkanLaporan() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(model);

        Connection conn = koneksi.getConnection();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Koneksi ke database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (jRadioButton1.isSelected()) {
                jLabel4.setText("Laporan Seluruh Data Buku");
                jLabel5.setText("Periode : Semua Periode");
                
                model.addColumn("ID Buku");
                model.addColumn("Judul Buku");
                model.addColumn("Pengarang");
                model.addColumn("Penerbit");
                model.addColumn("Tahun Terbit");
                model.addColumn("Kategori");
                model.addColumn("Stok");

                String sql = "SELECT id_buku, judul_buku, pengarang, penerbit, tahun_terbit, kategori, stok FROM buku";
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("id_buku"),
                        rs.getString("judul_buku"),
                        rs.getString("pengarang"),
                        rs.getString("penerbit"),
                        rs.getString("tahun_terbit"),
                        rs.getString("kategori"),
                        rs.getInt("stok")
                    });
                }
                rs.close();
                stmt.close();

            } else if (jRadioButton2.isSelected()) {
                jLabel4.setText("Laporan Daftar Anggota");
                jLabel5.setText("Periode : Semua Periode");
                
                model.addColumn("ID Anggota");
                model.addColumn("Nama Anggota");
                model.addColumn("Jenis Kelamin");
                model.addColumn("Telepon");
                model.addColumn("Alamat");

                String sql = "SELECT id_anggota, nama_anggota, jenis_kelamin, no_telp, alamat FROM anggota";
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("id_anggota"),
                        rs.getString("nama_anggota"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("no_telp"),
                        rs.getString("alamat")
                    });
                }
                rs.close();
                stmt.close();

            } else if (jRadioButton3.isSelected()) {
                Date dari = jDateChooser1.getDate();
                Date sampai = jDateChooser2.getDate();
                
                jLabel4.setText("Laporan Transaksi Peminjaman");
                if (dari != null && sampai != null) {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    jLabel5.setText("Periode : " + sdf.format(dari) + " s/d " + sdf.format(sampai));
                } else {
                    jLabel5.setText("Periode : Semua Periode");
                }

                model.addColumn("ID Pinjam");
                model.addColumn("Tgl Pinjam");
                model.addColumn("Nama Anggota");
                model.addColumn("Judul Buku");
                model.addColumn("Tgl Kembali");
                model.addColumn("Status");

                String sql;
                PreparedStatement pstmt = null;
                Statement stmt = null;
                ResultSet rs = null;

                if (dari != null && sampai != null) {
                    sql = "SELECT p.id_pinjam, p.tanggal_pinjam, a.nama_anggota, b.judul_buku, dp.tanggal_kembali, dp.status "
                        + "FROM peminjaman p "
                        + "JOIN anggota a ON p.id_anggota = a.id_anggota "
                        + "JOIN detail_peminjaman dp ON p.id_pinjam = dp.id_pinjam "
                        + "JOIN buku b ON dp.id_buku = b.id_buku "
                        + "WHERE p.tanggal_pinjam >= ? AND p.tanggal_pinjam <= ?";
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setDate(1, new java.sql.Date(dari.getTime()));
                    pstmt.setDate(2, new java.sql.Date(sampai.getTime()));
                    rs = pstmt.executeQuery();
                } else {
                    sql = "SELECT p.id_pinjam, p.tanggal_pinjam, a.nama_anggota, b.judul_buku, dp.tanggal_kembali, dp.status "
                        + "FROM peminjaman p "
                        + "JOIN anggota a ON p.id_anggota = a.id_anggota "
                        + "JOIN detail_peminjaman dp ON p.id_pinjam = dp.id_pinjam "
                        + "JOIN buku b ON dp.id_buku = b.id_buku";
                    stmt = conn.createStatement();
                    rs = stmt.executeQuery(sql);
                }

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                while (rs.next()) {
                    Date tglPinjam = rs.getDate("tanggal_pinjam");
                    Date tglKembali = rs.getDate("tanggal_kembali");
                    model.addRow(new Object[]{
                        rs.getString("id_pinjam"),
                        tglPinjam != null ? sdf.format(tglPinjam) : "",
                        rs.getString("nama_anggota"),
                        rs.getString("judul_buku"),
                        tglKembali != null ? sdf.format(tglKembali) : "",
                        rs.getString("status")
                    });
                }
                rs.close();
                if (pstmt != null) pstmt.close();
                if (stmt != null) stmt.close();

            } else if (jRadioButton4.isSelected()) {
                Date dari = jDateChooser1.getDate();
                Date sampai = jDateChooser2.getDate();

                jLabel4.setText("Laporan Pengembalian & Denda");
                if (dari != null && sampai != null) {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    jLabel5.setText("Periode : " + sdf.format(dari) + " s/d " + sdf.format(sampai));
                } else {
                    jLabel5.setText("Periode : Semua Periode");
                }

                model.addColumn("ID Kembali");
                model.addColumn("ID Pinjam");
                model.addColumn("Tgl Kembali");
                model.addColumn("Nama Anggota");
                model.addColumn("Terlambat (Hari)");
                model.addColumn("Denda");

                String sql;
                PreparedStatement pstmt = null;
                Statement stmt = null;
                ResultSet rs = null;

                if (dari != null && sampai != null) {
                    sql = "SELECT pg.id_kembali, pg.id_pinjam, pg.tanggal_kembali, pg.terlambat, a.nama_anggota, COALESCE(d.jumlah_denda, 0) AS jumlah_denda "
                        + "FROM pengembalian pg "
                        + "JOIN peminjaman p ON pg.id_pinjam = p.id_pinjam "
                        + "JOIN anggota a ON p.id_anggota = a.id_anggota "
                        + "LEFT JOIN denda d ON pg.id_kembali = d.id_kembali "
                        + "WHERE pg.tanggal_kembali >= ? AND pg.tanggal_kembali <= ?";
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setDate(1, new java.sql.Date(dari.getTime()));
                    pstmt.setDate(2, new java.sql.Date(sampai.getTime()));
                    rs = pstmt.executeQuery();
                } else {
                    sql = "SELECT pg.id_kembali, pg.id_pinjam, pg.tanggal_kembali, pg.terlambat, a.nama_anggota, COALESCE(d.jumlah_denda, 0) AS jumlah_denda "
                        + "FROM pengembalian pg "
                        + "JOIN peminjaman p ON pg.id_pinjam = p.id_pinjam "
                        + "JOIN anggota a ON p.id_anggota = a.id_anggota "
                        + "LEFT JOIN denda d ON pg.id_kembali = d.id_kembali";
                    stmt = conn.createStatement();
                    rs = stmt.executeQuery(sql);
                }

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                while (rs.next()) {
                    Date tglKembali = rs.getDate("tanggal_kembali");
                    int denda = rs.getInt("jumlah_denda");
                    String formattedDenda = "Rp " + String.format("%,d", denda);
                    model.addRow(new Object[]{
                        rs.getInt("id_kembali"),
                        rs.getString("id_pinjam"),
                        tglKembali != null ? sdf.format(tglKembali) : "",
                        rs.getString("nama_anggota"),
                        rs.getInt("terlambat"),
                        formattedDenda
                    });
                }
                rs.close();
                if (pstmt != null) pstmt.close();
                if (stmt != null) stmt.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private JasperPrint generateJasperPrint() throws Exception {
        String jrxmlName = "";
        Map<String, Object> parameters = new HashMap<>();

        if (jRadioButton1.isSelected()) {
            jrxmlName = "laporan_buku.jrxml";
        } else if (jRadioButton2.isSelected()) {
            jrxmlName = "laporan_anggota.jrxml";
        } else if (jRadioButton3.isSelected()) {
            jrxmlName = "laporan_peminjaman.jrxml";
            Date dari = jDateChooser1.getDate();
            Date sampai = jDateChooser2.getDate();
            if (dari == null) dari = new Date(0);
            if (sampai == null) sampai = new Date(2524608000000L);
            parameters.put("dari_tanggal", dari);
            parameters.put("sampai_tanggal", sampai);
        } else if (jRadioButton4.isSelected()) {
            jrxmlName = "laporan_pengembalian.jrxml";
            Date dari = jDateChooser1.getDate();
            Date sampai = jDateChooser2.getDate();
            if (dari == null) dari = new Date(0);
            if (sampai == null) sampai = new Date(2524608000000L);
            parameters.put("dari_tanggal", dari);
            parameters.put("sampai_tanggal", sampai);
        }

        Connection conn = koneksi.getConnection();
        if (conn == null) {
            throw new Exception("Koneksi database tidak tersedia.");
        }

        java.io.InputStream is = getClass().getResourceAsStream("/report/" + jrxmlName);
        if (is == null) {
            java.io.File file = new java.io.File("src/report/" + jrxmlName);
            if (file.exists()) {
                is = new java.io.FileInputStream(file);
            } else {
                throw new java.io.FileNotFoundException("Template " + jrxmlName + " tidak ditemukan.");
            }
        }

        JasperDesign jasperDesign = JRXmlLoader.load(is);
        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
        return jasperPrint;
    }

    private void cetakLaporan() {
        if (jRadioButton3.isSelected() || jRadioButton4.isSelected()) {
            Date dari = jDateChooser1.getDate();
            Date sampai = jDateChooser2.getDate();
            if (dari != null && sampai != null && dari.after(sampai)) {
                JOptionPane.showMessageDialog(this, "Tanggal awal tidak boleh melebihi tanggal akhir!", "Filter Salah", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        try {
            setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
            JasperPrint jasperPrint = generateJasperPrint();
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak laporan:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            setCursor(java.awt.Cursor.getDefaultCursor());
        }
    }

    private void exportPDF() {
        if (jRadioButton3.isSelected() || jRadioButton4.isSelected()) {
            Date dari = jDateChooser1.getDate();
            Date sampai = jDateChooser2.getDate();
            if (dari != null && sampai != null && dari.after(sampai)) {
                JOptionPane.showMessageDialog(this, "Tanggal awal tidak boleh melebihi tanggal akhir!", "Filter Salah", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Laporan PDF");
        fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Documents (*.pdf)", "pdf"));
        
        String defaultName = "";
        if (jRadioButton1.isSelected()) defaultName = "Laporan_Buku.pdf";
        else if (jRadioButton2.isSelected()) defaultName = "Laporan_Anggota.pdf";
        else if (jRadioButton3.isSelected()) defaultName = "Laporan_Peminjaman.pdf";
        else if (jRadioButton4.isSelected()) defaultName = "Laporan_Pengembalian.pdf";
        fileChooser.setSelectedFile(new java.io.File(defaultName));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            String path = fileToSave.getAbsolutePath();
            if (!path.toLowerCase().endsWith(".pdf")) {
                path += ".pdf";
            }

            try {
                setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
                JasperPrint jasperPrint = generateJasperPrint();
                JasperExportManager.exportReportToPdfFile(jasperPrint, path);
                JOptionPane.showMessageDialog(this, "Laporan berhasil diexport ke PDF!\nLokasi: " + path, "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal mengexport laporan ke PDF:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } finally {
                setCursor(java.awt.Cursor.getDefaultCursor());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
