/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Pengembalian extends javax.swing.JFrame {

    private java.util.List<String> listIdPinjam = new java.util.ArrayList<>();
    private boolean isFiltering = false;

    public Pengembalian() {
        initComponents();
        setLocationRelativeTo(null);
        styleComponents();
        jDateChooser1.setDate(new java.util.Date());
        tidkembali.setEditable(false);

        autonumber();
        // Popups will dynamically load when 'Cari' is clicked
        setupDatePickerListener();
    }

    private void styleComponents() {
        // Table Header Styling - Matching Image Reference (Light Blue Background, Dark
        // Blue Text)
        tabelKmbl.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                javax.swing.JLabel label = (javax.swing.JLabel) super.getTableCellRendererComponent(table, value,
                        isSelected, hasFocus, row, column);
                label.setBackground(new java.awt.Color(234, 241, 248)); // Light blue/gray background
                label.setForeground(new java.awt.Color(0, 51, 102)); // Dark blue text
                label.setFont(new java.awt.Font("Segoe UI", 1, 12));
                label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                label.setBorder(
                        javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));
                return label;
            }
        });
        tabelKmbl.setRowHeight(35); // Increased row height for better readability
        tabelKmbl.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));
        tabelKmbl.setGridColor(new java.awt.Color(230, 230, 230));
        tabelKmbl.setSelectionBackground(new java.awt.Color(235, 245, 255));
        tabelKmbl.setSelectionForeground(java.awt.Color.BLACK);

        // Adjust Column Widths
        tabelKmbl.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelKmbl.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelKmbl.getColumnModel().getColumn(2).setPreferredWidth(300);
        tabelKmbl.getColumnModel().getColumn(3).setPreferredWidth(200);
        tabelKmbl.getColumnModel().getColumn(4).setPreferredWidth(200);
        tabelKmbl.getColumnModel().getColumn(5).setPreferredWidth(150);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        panelJudul = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        lblidkembali = new javax.swing.JLabel();
        lbltanggalkembali = new javax.swing.JLabel();
        lblidpinjam = new javax.swing.JLabel();
        tidkembali = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtIdPinjam = new javax.swing.JTextField();
        btnCariPinjam = new javax.swing.JButton();
        panelTabel = new javax.swing.JPanel();
        scrolltabel = new javax.swing.JScrollPane();
        tabelKmbl = new javax.swing.JTable();
        panelAksi = new javax.swing.JPanel();
        lblstatus = new javax.swing.JLabel();
        btnproses = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        panelUtama.setBackground(new java.awt.Color(245, 247, 247));

        panelHeader.setBackground(new java.awt.Color(99, 102, 241));

        lblHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/loopback.png"))); // NOI18N
        lblHeader.setText(" Sistem Informasi Manajemen Perpustakaan");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        panelJudul.setBackground(new java.awt.Color(245, 247, 247));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("Pengembalian Buku");

        javax.swing.GroupLayout panelJudulLayout = new javax.swing.GroupLayout(panelJudul);
        panelJudul.setLayout(panelJudulLayout);
        panelJudulLayout.setHorizontalGroup(
            panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudulLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblJudul)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        panelJudulLayout.setVerticalGroup(
            panelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblJudul)
        );

        panelForm.setBackground(new java.awt.Color(245, 247, 247));

        lblidkembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblidkembali.setText("ID Kembali");

        lbltanggalkembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltanggalkembali.setText("Tanggal Kembali");

        lblidpinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblidpinjam.setText("ID Pinjam");

        tidkembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtIdPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCariPinjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCariPinjam.setText("Cari");
        btnCariPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPinjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidkembali)
                    .addComponent(lbltanggalkembali)
                    .addComponent(lblidpinjam))
                .addGap(81, 81, 81)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tidkembali)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(txtIdPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 386, Short.MAX_VALUE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblidkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbltanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTabel.setBackground(new java.awt.Color(245, 247, 247));
        panelTabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Buku yang Dikembalikan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        tabelKmbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelKmbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Buku", "Judul Buku", "Tgl Pinjam", "Tgl Kembali", "Terlambat (Hari)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrolltabel.setViewportView(tabelKmbl);

        lblstatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblstatus.setText("Status: -");
        lblstatus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblstatusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelAksiLayout = new javax.swing.GroupLayout(panelAksi);
        panelAksi.setLayout(panelAksiLayout);
        panelAksiLayout.setHorizontalGroup(
            panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAksiLayout.createSequentialGroup()
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        panelAksiLayout.setVerticalGroup(
            panelAksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAksiLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnproses.setBackground(new java.awt.Color(40, 167, 69));
        btnproses.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnproses.setForeground(new java.awt.Color(255, 255, 255));
        btnproses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/train-front.png"))); // NOI18N
        btnproses.setText("Proses Kembali");
        btnproses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(108, 117, 125));
        btnbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow-back-up-double.png"))); // NOI18N
        btnbatal.setText("Kembali");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addComponent(panelAksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnproses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addComponent(scrolltabel)
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrolltabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTabelLayout.createSequentialGroup()
                        .addComponent(btnproses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(panelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPinjamActionPerformed
        // TODO add your handling code here:
         javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Cari Data Pinjam", true);
        dialog.setSize(600, 400);
        dialog.setLocationRelativeTo(this);

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel.setBackground(new java.awt.Color(245, 247, 247));

        // Top Panel with Search
        javax.swing.JPanel topPanel = new javax.swing.JPanel(new java.awt.BorderLayout(5, 0));
        topPanel.setOpaque(false);
        javax.swing.JTextField txtSearch = new javax.swing.JTextField();
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14));
        topPanel.add(new javax.swing.JLabel("Cari (ID/Nama): "), java.awt.BorderLayout.WEST);
        topPanel.add(txtSearch, java.awt.BorderLayout.CENTER);

        // Table
        javax.swing.JTable table = new javax.swing.JTable();
        table.setFont(new java.awt.Font("Segoe UI", 0, 14));
        table.setRowHeight(30);
        table.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 14));
        table.getTableHeader().setBackground(new java.awt.Color(234, 241, 248));
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Pinjam", "ID Anggota", "Nama Anggota"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(model);
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(table);

        panel.add(topPanel, java.awt.BorderLayout.NORTH);
        panel.add(scroll, java.awt.BorderLayout.CENTER);
        dialog.add(panel);

        Runnable loadData = () -> {
            model.setRowCount(0);
            String search = txtSearch.getText().trim();
            String sql = "SELECT DISTINCT dp.id_pinjam, p.id_anggota, a.nama_anggota FROM detail_peminjaman dp " +
                         "JOIN peminjaman p ON dp.id_pinjam = p.id_pinjam " +
                         "JOIN anggota a ON p.id_anggota = a.id_anggota " +
                         "WHERE dp.id_pinjam LIKE ? OR a.nama_anggota LIKE ? ORDER BY dp.id_pinjam DESC";
            try (Connection conn = koneksi.koneksi.getConnection();
                 PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1, "%" + search + "%");
                pst.setString(2, "%" + search + "%");
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("id_pinjam"), rs.getString("id_anggota"), rs.getString("nama_anggota")});
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        };

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loadData.run();
            }
        });

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int row = table.getSelectedRow();
                    if (row != -1) {
                        txtIdPinjam.setText(model.getValueAt(row, 0).toString());
                        dialog.dispose();
                        loadBukuPinjam();
                    }
                }
            }
        });

        loadData.run();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnCariPinjamActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnprosesActionPerformed
        String idKembaliStr = tidkembali.getText().trim();
        String selectedPinjam = txtIdPinjam.getText().trim();

        if (idKembaliStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Pengembalian kosong!");
            return;
        }
        if (selectedPinjam.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap pilih ID Pinjam!");
            return;
        }

        String idPinjam = selectedPinjam;
        DefaultTableModel model = (DefaultTableModel) tabelKmbl.getModel();
        int rowCount = model.getRowCount();
        if (rowCount == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada buku untuk dikembalikan!");
            return;
        }

        // Calculate max late days
        int maxTerlambat = 0;
        for (int i = 0; i < rowCount; i++) {
            int terlambat = Integer.parseInt(model.getValueAt(i, 5).toString());
            if (terlambat > maxTerlambat) {
                maxTerlambat = terlambat;
            }
        }

        Date returnDate = jDateChooser1.getDate();
        if (returnDate == null) {
            returnDate = new Date();
        }
        String returnDateStr = new SimpleDateFormat("yyyy-MM-dd").format(returnDate);

        // Parse visual id_kembali string (e.g. "K001" -> 1)
        int idKembaliInt = 1;
        try {
            idKembaliInt = Integer.parseInt(idKembaliStr.replaceAll("[^0-9]", ""));
        } catch (NumberFormatException e) {
            // fallback
        }

        Connection conn = koneksi.koneksi.getConnection();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Koneksi database gagal!");
            return;
        }

        try {
            conn.setAutoCommit(false);

            try (Statement st = conn.createStatement()) {
                // Disable foreign key checks so we can delete the borrow record while
                // referenced
                st.execute("SET FOREIGN_KEY_CHECKS = 0");

                // 1. Insert into pengembalian
                String sqlInsert = "INSERT INTO pengembalian (id_kembali, id_pinjam, tanggal_kembali, terlambat) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstInsert = conn.prepareStatement(sqlInsert)) {
                    pstInsert.setInt(1, idKembaliInt);
                    pstInsert.setString(2, idPinjam);
                    pstInsert.setString(3, returnDateStr);
                    pstInsert.setInt(4, maxTerlambat);
                    pstInsert.executeUpdate();
                }

                // 2. Restock all books in detail_peminjaman
                String sqlRestock = "UPDATE buku SET stok = stok + 1 WHERE id_buku = ?";
                try (PreparedStatement pstRestock = conn.prepareStatement(sqlRestock)) {
                    for (int i = 0; i < rowCount; i++) {
                        String idBuku = model.getValueAt(i, 1).toString();
                        pstRestock.setString(1, idBuku);
                        pstRestock.addBatch();
                    }
                    pstRestock.executeBatch();
                }

                // 3. Delete from detail_peminjaman
                String sqlDeleteDetail = "DELETE FROM detail_peminjaman WHERE id_pinjam = ?";
                try (PreparedStatement pstDelDetail = conn.prepareStatement(sqlDeleteDetail)) {
                    pstDelDetail.setString(1, idPinjam);
                    pstDelDetail.executeUpdate();
                }

                // Enable foreign key checks back
                st.execute("SET FOREIGN_KEY_CHECKS = 1");
            }

            conn.commit();
            JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan!");

            // Clean up UI & reload
            autonumber();
            txtIdPinjam.setText("");
            model.setRowCount(0);
            lblstatus.setText("Status: -");
            lblstatus.setForeground(java.awt.Color.BLACK);
            jDateChooser1.setDate(new Date());

        } catch (Exception e) {
            try {
                conn.rollback();
            } catch (SQLException ex) {
                // ignore
            }
            // Ensure foreign key checks are re-enabled
            try (Statement st = conn.createStatement()) {
                st.execute("SET FOREIGN_KEY_CHECKS = 1");
            } catch (Exception ex) {
                // ignore
            }
            JOptionPane.showMessageDialog(this, "Gagal memproses pengembalian: " + e.getMessage());
        } finally {
            try {
                conn.setAutoCommit(true);
            } catch (SQLException ex) {
                // ignore
            }
        }
    }// GEN-LAST:event_btnprosesActionPerformed

    private void autonumber() {
        Connection conn = koneksi.koneksi.getConnection();
        if (conn == null)
            return;
        try (Statement st = conn.createStatement();
                ResultSet rs = st
                        .executeQuery("SELECT id_kembali FROM pengembalian ORDER BY id_kembali DESC LIMIT 1")) {
            if (rs.next()) {
                String lastId = rs.getString("id_kembali");
                String numberPart = lastId.replaceAll("[^0-9]", "");
                if (numberPart.isEmpty()) {
                    tidkembali.setText("K001");
                } else {
                    int num = Integer.parseInt(numberPart) + 1;
                    tidkembali.setText(String.format("K%03d", num));
                }
            } else {
                tidkembali.setText("K001");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal generate ID: " + e.getMessage());
        }
    }

    private void setupDatePickerListener() {
        jDateChooser1.addPropertyChangeListener("date", evt -> {
            String selected = txtIdPinjam.getText().trim();
            if (!selected.isEmpty()) {
                loadBukuPinjam();
            }
        });
    }

    private void loadBukuPinjam() {
        DefaultTableModel model = (DefaultTableModel) tabelKmbl.getModel();
        model.setRowCount(0);

        String selected = txtIdPinjam.getText().trim();
        if (selected.isEmpty()) {
            lblstatus.setText("Status: -");
            lblstatus.setForeground(java.awt.Color.BLACK);
            return;
        }

        String idPinjam = selected;
        Date actualReturnDate = jDateChooser1.getDate();
        if (actualReturnDate == null) {
            actualReturnDate = new Date();
        }

        Connection conn = koneksi.koneksi.getConnection();
        if (conn == null)
            return;

        String sql = "SELECT dp.id_buku, b.judul_buku, p.tanggal_pinjam, dp.tanggal_kembali "
                + "FROM detail_peminjaman dp "
                + "JOIN peminjaman p ON dp.id_pinjam = p.id_pinjam "
                + "JOIN buku b ON dp.id_buku = b.id_buku "
                + "WHERE dp.id_pinjam = ?";

        int no = 1;
        int maxTerlambat = 0;

        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, idPinjam);
            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    String idBuku = rs.getString("id_buku");
                    String judul = rs.getString("judul_buku");
                    Date tglPinjam = rs.getDate("tanggal_pinjam");
                    Date tglKembaliPlan = rs.getDate("tanggal_kembali");

                    int terlambat = hitungTerlambat(tglKembaliPlan, actualReturnDate);
                    if (terlambat > maxTerlambat) {
                        maxTerlambat = terlambat;
                    }

                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String tglPinjamStr = tglPinjam != null ? sdf.format(tglPinjam) : "";
                    String tglKembaliPlanStr = tglKembaliPlan != null ? sdf.format(tglKembaliPlan) : "";

                    model.addRow(new Object[] {
                            no++,
                            idBuku,
                            judul,
                            tglPinjamStr,
                            tglKembaliPlanStr,
                            terlambat
                    });
                }
            }

            if (no > 1) {
                if (maxTerlambat > 0) {
                    lblstatus.setText("Status: Terlambat (" + maxTerlambat + " Hari)");
                    lblstatus.setForeground(new java.awt.Color(220, 53, 69)); // Bootstrap Red
                } else {
                    lblstatus.setText("Status: Tepat Waktu");
                    lblstatus.setForeground(new java.awt.Color(40, 167, 69)); // Bootstrap Green
                }
            } else {
                lblstatus.setText("Status: -");
                lblstatus.setForeground(java.awt.Color.BLACK);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat buku: " + e.getMessage());
        }
    }

    private int hitungTerlambat(Date tglKembaliPlan, Date tglKembaliActual) {
        if (tglKembaliPlan == null || tglKembaliActual == null)
            return 0;

        java.util.Calendar cal1 = java.util.Calendar.getInstance();
        cal1.setTime(tglKembaliPlan);
        cal1.set(java.util.Calendar.HOUR_OF_DAY, 0);
        cal1.set(java.util.Calendar.MINUTE, 0);
        cal1.set(java.util.Calendar.SECOND, 0);
        cal1.set(java.util.Calendar.MILLISECOND, 0);

        java.util.Calendar cal2 = java.util.Calendar.getInstance();
        cal2.setTime(tglKembaliActual);
        cal2.set(java.util.Calendar.HOUR_OF_DAY, 0);
        cal2.set(java.util.Calendar.MINUTE, 0);
        cal2.set(java.util.Calendar.SECOND, 0);
        cal2.set(java.util.Calendar.MILLISECOND, 0);

        if (cal2.after(cal1)) {
            long diff = cal2.getTimeInMillis() - cal1.getTimeInMillis();
            return (int) (diff / (24 * 60 * 60 * 1000));
        }
        return 0;
    }

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        new tampilanawal.dashboard().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnbatalActionPerformed

    private void lblstatusAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_lblstatusAncestorAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_lblstatusAncestorAdded
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariPinjam;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnproses;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblidkembali;
    private javax.swing.JLabel lblidpinjam;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lbltanggalkembali;
    private javax.swing.JPanel panelAksi;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JScrollPane scrolltabel;
    private javax.swing.JTable tabelKmbl;
    private javax.swing.JTextField tidkembali;
    private javax.swing.JTextField txtIdPinjam;
    // End of variables declaration//GEN-END:variables
}
